### ISSUE TITLE
Need to run twice to get output

### ISSUE THREAD

**Issue by ifuchs** [magico13/PyEmVue#14]
I am running this script:
`from pyemvue.enums import Scale, Unit
vue = pyemvue.PyEmVue()
vue.login(username='', password='', token_storage_file='keys.json')

devices = vue.get_devices()
deviceGids = []
for device in devices:
    deviceGids.append(device.device_gid)

channel_usage_list = vue.get_devices_usage(deviceGids, None, scale=Scale.SECOND.value,unit=Unit.KWH.value)
for channel in channel_usage_list:
    print("%.3f" % (channel.usage*3600), 'kwh')`

Most of the time, the first time I run it (after not running it for say an hour) I get no output. The second, and subsequent executions result in the expected output. Is this a problem with the server?

**Comment by magico13** [comment]
If you're not getting an exception then it's not the server returning an error, though the server could be returning no data. Since you say it's after an hour or so then it's possible that it's related to the authentication token expiring, though you should be getting a new one each time you run it if that's the exact script.

I'll have to do some testing. This might be related to an issue someone is seeing with the home assistant plugin where they are randomly not getting any data back from the same call.

**Comment by ifuchs** [comment]
Other than the password and userid , that is the precise script. I just tried it again and got the same result (no data followed by data).

**Comment by magico13** [comment]
I'm trying to see if I can replicate this but not having luck, unfortunately it's working fine for me. A few things to try:
1. It looks like you want the usage over an hour but are getting the usage for the last second, so change the scale to `Scale.HOUR.value` and leave the rest of the script the same and it should report for usage over the last hour rather than the last second.
2. Pass an explicit time rather than None. None should result in it doing `datetime.datetime.utcnow()` but you could specify a time yourself. Note that right now it's gotta be a timezone unaware, UTC based time.
3. Add a wait for a second or two after the login before requesting the data. Or call it once and if you get nothing back call it again within the same script.

What timezone are you in? I know there's an issue open for BST in the home assistant plugin which I suspect is just due to them going from lining up with UTC to being off by one.

**Comment by ifuchs** [comment]
I am asking for the Sec value and multiplying to get the current utilization in KWH. The hr value you suggest is actually a quarter hour value (it is computed 4 times/ hr.) The wait after login or multiple calls may work.

**Comment by magico13** [comment]
Cleaning up old issues so I'm closing this one out.
