### ISSUE TITLE
1MIN scale not working

### ISSUE THREAD

**Issue by c3p0vsr2d2** [magico13/PyEmVue#37]
I get a 404 error with a scale of 1MIN, the error is the following:

requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.emporiaenergy.com/AppAPI?apiMethod=getChartUsage&deviceGid=XXXXX&channel=1,2,3&start=2022-06-03T23:24:44.206428Z&end=2022-06-05T23:24:44.206467Z&scale=1MIN&energyUnit=KilowattHours

**Comment by magico13** [comment]
Try `deviceGids` instead of `deviceGid` even though you're only using one

**Comment by magico13** [comment]
Sorry, I saw the URL and my brain jumped to hitting the API directly, I forgot that the URLs are baked into the library. Yeah, most likely they have implemented API-side restrictions to limit the amount of data you can request at one time. I didn't catch that you were requesting two days worth of data.

@Cuervocartoon you probably have a similar problem since it looks like you're getting 1 week of data at the 15 minute scale, try limiting that to a day at a time, or even 12 hours if one day isn't small enough.

**Comment by Cuervocartoon** [comment]
Thank you for the fast reply, it was right the problem.

**Comment by c3p0vsr2d2** [comment]
Thanks @magico13, I will close this issue for now. Seems like some restrictions being added on Vue's side. Thanks for the help.
