### ISSUE TITLE
[feature request] Emulate wall plug?

### ISSUE THREAD

**Issue by ankushg** [magico13/PyEmVue#54]
I've got a few smart plugs that report energy consumption, but they're not Emporia branded. 

Is it possible to emulate an Emporia plug and get third-party data into the official Emporia app?

**Comment by magico13** [comment]
The short answer is no, the API we've got access to only lets us read data and is different from the systems the hardware uses to write data. If you want to integrate different devices into one system I would suggest Home Assistant, otherwise Amazon Alexa, Google Home, or Apple Home may let you see everything in one place.

Emporia does seem to integrate some other devices into their app so there's a chance they could add something themselves, but the other devices they support don't overlap with devices they sell so most likely they would rather have you buy more of their plugs.

**Comment by ankushg** [comment]
Gotcha, thanks for the reply!

I’m already using home assistant so I’ll stick with that, just figured it
would have been cool to get the additional devices into Emporia’s official
app too :)

Thanks for maintaining this library and the HA integration!
