### ISSUE TITLE
Support for Bi-Directional Circuit.

### ISSUE THREAD

**Issue by diverdavis** [magico13/PyEmVue#85]
On Jun 27, 2024 Emporia released a new firmware that allows for a Circuit to be bi-directional. The emporiaenergy website now shows green when a circuit is producing power (similar to when you are producing more solar power then using on the mains). Home assistant still show the value as positive (using watts) where it should be a negative value (producing watts).

![Screenshot 2024-06-29 074151](https://github.com/magico13/PyEmVue/assets/18706444/906574a7-5fdf-49a8-9884-55c90e3569fe)

**Comment by magico13** [comment]
I am working on adding the support for this into PyEmVue, and then once it's in there I can add support in Home Assistant. Since this repo is for the backing PyEmVue library and not the Home Assistant integration, I'm going to close this issue and advise you to follow https://github.com/magico13/ha-emporia-vue/issues/290 for updates on the integration.
